### ISSUE TITLE
文件注释有乱码

### ISSUE THREAD

**Issue by FLOWERCLOUD** [Tencent/GAutomator#100]
注释乱码 
[乱码1](https://github.com/Tencent/GAutomator/blob/master/GAutomatorSdk/UnrealEngine/GAutomatorSdk/Plugins/GAutomator/Source/GAutomator/Private/UI/UIManager.h)
[乱码2](https://github.com/Tencent/GAutomator/blob/master/GAutomatorSdk/UnrealEngine/GAutomatorSdk/Plugins/GAutomator/Source/GAutomator/Private/UI/UIManager.cpp)

**Comment by David-pzk** [comment]
感谢FLOWERCLOUD的提醒，乱码问题已经修复并提交了，有其他问题欢迎咨询~~~

**Comment by prife** [comment]
fixed #96
