### ISSUE TITLE
Android系统UI控件如何处理？

### ISSUE THREAD

**Issue by skyseraph** [Tencent/GAutomator#24]
咨询下，Unity 游戏中出现Android UI控件，如Android的Dialog，GAutomator提供的API都无效了，有建议或解决方案么？ tkx

**Comment by wukenaihe** [comment]
框架内集成了xiaocong的框架，支持uiautomator的。我们的框架里面device.ui_device，就是AutomatorDevice的实例，是能够操作的。
我们这边device里面的login_qq_wechat_wait，就是操作标准控件

**Comment by skyseraph** [comment]
有sample可以参考么？ 例如当前游戏某场景A下弹出了Dialog B，可否写个简单Sample？ 谢谢。

**Comment by wukenaihe** [comment]
@skyseraph 内置使用的是该框架https://github.com/xiaocong/uiautomator，可以参考他写的文档

**Comment by skyseraph** [comment]
@wukenaihe 恩，click等操作简单，我的意思是一个完整的业务流程。 例如如何判断当前页面是Android弹窗还是Unity页面等，希望可以有个简单sample~
