### ISSUE TITLE
是否有计划支持unity PC版？

### ISSUE THREAD

**Issue by GlodenBoy** [Tencent/GAutomator#29]
不知道有没有计划支持PC版本，一般来说我们有时候不一定是每次都打出手机包

**Comment by wukenaihe** [comment]
@luoxiaoji IOS有计划支持，PC版没有计划

**Comment by luoxiaoji** [comment]
是不好移植吗， PC 版理论上应该是和手机版一样吧，ADB换成了 win 的API？

**Comment by wukenaihe** [comment]
@luoxiaoji 并不是，而是没收到多少需求。其实，只需要把jar换成pc上对应的功能就好了。一个是获取应用长宽，一个是输入touch时间。adb，都不需要了，因为能够直接通信
