### ISSUE TITLE
smcs.rsp, gmcs.rsp 两个文件如何编写，及放在何处？

### ISSUE THREAD

**Issue by zqlangzi** [Tencent/GAutomator#3]
![qq 20161212124123](https://cloud.githubusercontent.com/assets/11610548/21088222/5a9bada0-c068-11e6-8392-7876b1002e70.png)

unity中已经通过了宏编译WETEST_SDK控制是否接入sdk, 为何此处还要在python中再控制一次？ 还有具体的这段代码 def ModifyMacro该放在何处及如何初始化，请告知，谢谢。

**Comment by wukenaihe** [comment]
自动化通常会跟CI持续集成在一起，修改文件来控制宏定义通常是CI持续集成编译的时候用到的。如果你是桌面unityeditor编译的，这个可以忽略。可能是我没写清楚

**Comment by zqlangzi** [comment]
明白了，再次感谢提供了这么好的一个SDK~
