### ISSUE TITLE
今天突然运行报错

### ISSUE THREAD

**Issue by jyaxie** [Tencent/GAutomator#32]
之前用这个已经写完了主线任务的脚本，跑着也没啥问题，今天突然就运行报错了，报错信息如下

![ed2762cc-43e8-4667-827f-8ae46b953bed](https://user-images.githubusercontent.com/31148889/31044631-76cd1602-a605-11e7-83c4-ac047ac70801.jpg)
用wetest.apk那个小demo跑了一下也是一样的报错，求拯救！

**Comment by wukenaihe** [comment]
@jyaxie 请确认下，adb环境是否正常？大部分时候，这种错误都是adb环境出问题了

**Comment by jyaxie** [comment]
@wukenaihe 确实是adb出错，端口被第三方的手机助手占用了，现在问题已经解决了，感谢
