### ISSUE TITLE
自动记录和回放InputField

### ISSUE THREAD

**Issue by tryfore** [Tencent/GAutomator#36]
您好，问下关于在wiki中的自动录制与回放中，InputField值的记录与回放如何解决？如何在录制文件.txt中加入InputField的txt信息，然后在回放时实现自动赋值。

**Comment by wukenaihe** [comment]
@tryfore 不支持。你们可以自己定制。这块之前是试验产品，将源码和原理都放出去。我们这边不会再进行进一步开发
