### ISSUE TITLE
初始化成功，但GAutoMatorView报error

### ISSUE THREAD

**Issue by hungry0** [Tencent/GAutomator#44]
看日志可以看到：U3DAutomation Init OK. Version = 1.5.0 UIType = UGUI
但是view运行
![image](https://user-images.githubusercontent.com/13111009/39178011-4be01e50-47e3-11e8-9873-ac4486e2cf27.png)

**Comment by wukenaihe** [comment]
@hungry0 需要确保游戏已经来起来。还有检查下，你的环境里面是否有adb。where adb能够查看是否设置adb了
