### ISSUE TITLE
gameObject未显示

### ISSUE THREAD

**Issue by zqlangzi** [Tencent/GAutomator#5]
![3](https://cloud.githubusercontent.com/assets/11610548/21093189/78cffbc8-c08b-11e6-9b92-2d057c9a3c83.png)
![4](https://cloud.githubusercontent.com/assets/11610548/21093190/79a850d6-c08b-11e6-866d-b6fbc1034a37.jpg)

疑问1：如图3 Canvas/Panel/ 增加一kftest GameObject，打包后手机上看不到。
但调用 
e = engine.find_element("/Canvas/Panel/kftest")
engine.click(e) 
执行效果是有的，如图4所示。
疑问2：点击的位置没有按我所期待的那样在 Sample2 的右下角。不知道是否是与分辨率及 layout有关。

**Comment by wukenaihe** [comment]
用GAutomatorView选中/Canvas/Panel/kftest，会有红色的框圈范围来的。点击的位置时红色框的中心位置。
