### ISSUE TITLE
[同步游戏]同步不了图像

### ISSUE THREAD

**Issue by gzliuqingyun** [Tencent/GAutomator#57]
![image](https://user-images.githubusercontent.com/15082338/50580967-009ed700-0e90-11e9-8bb1-70f01a1d94d0.png)

**Comment by tianshanfz** [comment]
在问题发生后 立刻执行以下操作：
看下/data/local/tmp下的wetest.png内容是否正确。 
a.如果不正确试下adb shell screencap -p /data/local/tmp/wetest.png   是否能执行成功？
b.如果正确可以提供一下问题发生时 app/logs/目录下的log文件以及时间点？

**Comment by gzliuqingyun** [comment]
> 在问题发生后 立刻执行以下操作：
> 看下手机/data/local/tmp下的wetest.png内容是否正确。
> a.如果不正确试下adb shell screencap -p /data/local/tmp/wetest.png 是否能执行成功？
> b.如果正确可以提供一下问题发生时 app/logs/目录下的log文件以及时间点？

不正确，/data/local/tmp/目录下不存在wetest.png

**Comment by gzliuqingyun** [comment]
另，screencap功能正常

**Comment by tianshanfz** [comment]
@gzliuqingyun  QQ: 1508397022

**Comment by tianshanfz** [comment]
GautomatorView已更新，修复部分设备同步截图失败问题。http://cdn.wetest.qq.com/com/c/GAutomatorView.zip
