### ISSUE TITLE
GArecorder--Start recording, iOS设备无法connect。

### ISSUE THREAD

**Issue by dangdangma1989** [Tencent/GAutomator#62]
xcode: 10.1;
iphone: 12.1.2
python: 2.7

idevice_id -l 可拿到当前设备UDID

**Comment by tianshanfz** [comment]
是看不到设备还是连接没有画面。
如果是前者 按文档把环境变量里的device_id iproxy 拷贝到插件目录~/Library/Application\ Support/PyCharmCEXXXXXX/wetest_plugin_pycharm/
如果是后者，拷贝环境变量里的iproxy到上述目录，  并且看看按照设定的xcode路径和wdapath手动用命令是否能起wda和iproxy。
手动起wda的命令：
$PATH_TO_XCODEBUILD/xcodebuild  -project $PATH_TO_WDA/WebDriverAgent.xcodeproj test -scheme WebDriverAgentRunner -destination platform=iOS,id=$serial
手动能起的话 看看插件目录下面mobileservice.log里面有什么报错

**Comment by wennx1992** [comment]
@tianshanfz 看得到设备，connect后无限loading，按你的命令手动起wda后显示报错
Testing failed:
	WebDriverAgentRunner:
		WebDriverAgentRunner-Runner.app (468) encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted. (Underlying error: Crash: WebDriverAgentRunner-Runner (468): DYLD, Symbol not found: __XCTLoadTestConfiguration | Referenced from: /var/containers/Bundle/Application/8FF139E6-6EAF-4DE4-B994-BAC4F31D495A/WebDriverAgentRunner-Runner.app/WebDriverAgentRunner-Runner | Expected in: /private/var/containers/Bundle/Application/8FF139E6-6EAF-4DE4-B994-BAC4F31D495A/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest))

**Comment by wennx1992** [comment]
> @tianshanfz 看得到设备，connect后无限loading，按你的命令手动起wda后显示报错
> Testing failed:
> WebDriverAgentRunner:
> WebDriverAgentRunner-Runner.app (468) encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted. (Underlying error: Crash: WebDriverAgentRunner-Runner (468): DYLD, Symbol not found: __XCTLoadTestConfiguration | Referenced from: /var/containers/Bundle/Application/8FF139E6-6EAF-4DE4-B994-BAC4F31D495A/WebDriverAgentRunner-Runner.app/WebDriverAgentRunner-Runner | Expected in: /private/var/containers/Bundle/Application/8FF139E6-6EAF-4DE4-B994-BAC4F31D495A/WebDriverAgentRunner-Runner.app/Frameworks/XCTest.framework/XCTest))
> 
> 这里说是XCTest报错，我的Xcode是10.12的，外用Xcode9里的XCTest.framework覆盖过了

装了个Xcode10.0后已解决，发现还是XCTest的问题

**Comment by tianshanfz** [comment]
Xcode10.2 删除了部分私有API。参考https://github.com/iGhibli/iOS-DeviceSupport
