### ISSUE TITLE
'adb' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by giangnbd00352** [Tencent/GAutomator#74]
![Capture](https://user-images.githubusercontent.com/29310477/65684759-9fa4d800-e08a-11e9-9a5b-37976aa60929.PNG)

我按照说明操作，运行此错误后，如何解决？

**Comment by tianshanfz** [comment]
确保adb在你的环境变量中。

**Comment by giangnbd00352** [comment]
> 确保adb在你的环境变量中。

感谢您解决这个问题
